name: "Build and Delivery Docker Image"

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'feature/ci-docker-workflow'

jobs:
  docker:
    name: "Build and push Docker image to Docker Hub"
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: sidneijp/node_example:latest
  deploy-heroku:
    name: "Deploy on Heroku"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@2.1.17  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          app_name: ${{ secrets.HEROKU_APP_NAME }} # you aplication name
          dockerfile_path: '' # set the path to the folder wher the Dokerfile is located
          options: '' # Docker Build Options
          formation: '' # Docker Dyno Formation. By default is web
          